spring: 
  main:
    allow-bean-definition-overriding: true 
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
      bindings:
        user-in:
          destination: userpayload
          contentType: application/json
        user-out:
          destination: userpayload
          contentType: application/json
      default-binder: kafka
  data:
    cassandra:
      contact-points: 127.0.0.1
      username: harvey
      password: harvey 
    jpa:
      repositories:
        enabled: true       
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1W2w1s500.
  mail:
    host: smtp.gmail.com
    port: 587
    username: mymail@gmail.com
    password: mypassword
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com